from rest_framework import serializers

class MasterDataCreateSerializer(serializers.Serializer):
    code = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    name = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    title = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    company_name = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    supplier_name = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    description = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    contact_name = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    phone = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    email = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    address = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    location = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    category_id = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    category_name = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    category = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    sequence = serializers.IntegerField(required=False, allow_null=True, default=0)
    months = serializers.FloatField(required=False, allow_null=True)
    symbol = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    amount = serializers.FloatField(required=False, allow_null=True, default=0.0)
    status = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="ACTIVE")

class MasterDataUpdateSerializer(serializers.Serializer):
    name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    title = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    company_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    description = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    contact_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    phone = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    email = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    address = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    location = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    sequence = serializers.IntegerField(required=False, allow_null=True)
    months = serializers.FloatField(required=False, allow_null=True)
    symbol = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    amount = serializers.FloatField(required=False, allow_null=True)
    status = serializers.CharField(required=False, allow_null=True, allow_blank=True)

class MasterDataResponseSerializer(serializers.Serializer):
    id = serializers.CharField()
    code = serializers.CharField()
    name = serializers.CharField()
    description = serializers.CharField(allow_null=True, required=False)
    contact_name = serializers.CharField(allow_null=True, required=False)
    phone = serializers.CharField(allow_null=True, required=False)
    email = serializers.CharField(allow_null=True, required=False)
    address = serializers.CharField(allow_null=True, required=False)
    location = serializers.CharField(allow_null=True, required=False)
    sequence = serializers.IntegerField(allow_null=True, required=False, default=0)
    months = serializers.FloatField(allow_null=True, required=False)
    symbol = serializers.CharField(allow_null=True, required=False)
    amount = serializers.FloatField(allow_null=True, required=False)
    status = serializers.CharField()
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()


class CompanyUpdateSerializer(serializers.Serializer):
    name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    phone = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    website = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    address = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    description = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    currency = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    timezone = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    date_format = serializers.CharField(required=False, allow_null=True, allow_blank=True)

class CompanyResponseSerializer(serializers.Serializer):
    id = serializers.CharField()
    name = serializers.CharField()
    phone = serializers.CharField(allow_null=True, required=False)
    website = serializers.CharField(allow_null=True, required=False)
    address = serializers.CharField(allow_null=True, required=False)
    description = serializers.CharField(allow_null=True, required=False)
    currency = serializers.CharField()
    timezone = serializers.CharField()
    date_format = serializers.CharField()
